// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using duybao.data;

#nullable disable

namespace duybao.data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260618083203_SeedFashionData")]
    partial class SeedFashionData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("duybao.data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cập nhật những xu hướng thời trang mới nhất",
                            Name = "Xu hướng thời trang"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mẹo phối đồ phong cách và ấn tượng",
                            Name = "Bí quyết phối đồ"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Thông tin sự kiện và ưu đãi đặc biệt",
                            Name = "Sự kiện & Khuyến mãi"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Chia sẻ bí quyết chăm sóc sắc đẹp",
                            Name = "Tư vấn làm đẹp"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tài liệu ASP.NET Core và SQL Server.",
                            Name = "Góc lập trình viên"
                        });
                });

            modelBuilder.Entity("duybao.data.Entities.CategoryProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CategoriesProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Thoải mái, dễ chịu cho những ngày ở nhà",
                            Name = "Trang phục nữ mặc ở nhà"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lịch lãm và chuyên nghiệp cho phái mạnh",
                            Name = "Vest & Âu phục nam"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sang trọng cho những dịp đặc biệt",
                            Name = "Đầm dạ hội quý phái"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Thanh lịch và tinh tế cho nữ công sở",
                            Name = "Thời trang công sở nữ"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Hoàn thiện phong cách của bạn",
                            Name = "Phụ kiện thời trang"
                        });
                });

            modelBuilder.Entity("duybao.data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("duybao.data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("duybao.data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("duybao.data.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Content = "Khám phá những bí quyết phối đồ công sở giúp bạn luôn thanh lịch và chuyên nghiệp.",
                            CreatedDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/600x350/ffe0e0/999?text=Thời+Trang+Nữ",
                            Title = "Bí quyết phối đồ công sở thanh lịch cho nữ"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Content = "Cập nhật những xu hướng vest nam mới nhất năm 2026.",
                            CreatedDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/600x350/e0e0ff/999?text=Vest+Nam+2026",
                            Title = "Xu hướng vest nam 2026 - Lịch lãm và hiện đại"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Content = "Cách chọn đầm dạ hội phù hợp với vóc dáng và phong cách.",
                            CreatedDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/600x350/ffe0ff/999?text=Đầm+Dạ+Hội",
                            Title = "Đầm dạ hội - Lựa chọn hoàn hảo cho mọi sự kiện"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Content = "Xu hướng thời trang bền vững đang len lỏi vào môi trường công sở.",
                            CreatedDate = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/600x350/e0ffe0/999?text=Công+Sở+Bền+Vững",
                            Title = "Phong cách thời trang công sở bền vững"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Content = "Từ túi xách, giày dép đến trang sức - những phụ kiện giúp bạn hoàn thiện phong cách.",
                            CreatedDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/600x350/fff0e0/999?text=Phụ+Kiện",
                            Title = "Phụ kiện thời trang không thể thiếu cho nữ"
                        });
                });

            modelBuilder.Entity("duybao.data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryProductId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryProductId = 3,
                            ImageUrl = "https://placehold.co/400x500/eee/999?text=Đầm+Dạ+Hội",
                            Name = "Đầm dạ hội quý phái",
                            Price = 2400000m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 2,
                            CategoryProductId = 2,
                            ImageUrl = "https://placehold.co/400x500/eee/999?text=Vest+Nam",
                            Name = "Vest nam cao cấp",
                            Price = 3200000m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 3,
                            CategoryProductId = 4,
                            ImageUrl = "https://placehold.co/400x500/eee/999?text=Sơ+Mi+Nữ",
                            Name = "Áo sơ mi công sở nữ",
                            Price = 550000m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 4,
                            CategoryProductId = 4,
                            ImageUrl = "https://placehold.co/400x500/eee/999?text=Chân+Váy",
                            Name = "Chân váy bút chì",
                            Price = 680000m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 5,
                            CategoryProductId = 2,
                            ImageUrl = "https://placehold.co/400x500/eee/999?text=Quần+Tây",
                            Name = "Quần tây nam",
                            Price = 890000m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 6,
                            CategoryProductId = 4,
                            ImageUrl = "https://placehold.co/400x500/eee/999?text=Đầm+Công+Sở",
                            Name = "Đầm công sở thanh lịch",
                            Price = 1250000m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 7,
                            CategoryProductId = 1,
                            ImageUrl = "https://placehold.co/400x500/eee/999?text=Blazer+Nữ",
                            Name = "Áo blazer nữ",
                            Price = 1850000m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 8,
                            CategoryProductId = 2,
                            ImageUrl = "https://placehold.co/400x500/eee/999?text=Sơ+Mi+Trắng",
                            Name = "Sơ mi nam trắng",
                            Price = 450000m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 9,
                            CategoryProductId = 4,
                            ImageUrl = "https://placehold.co/400x500/eee/999?text=Vest+Nữ",
                            Name = "Bộ vest nữ công sở",
                            Price = 2800000m,
                            StockQuantity = 7
                        });
                });

            modelBuilder.Entity("duybao.data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Quản trị viên hệ thống",
                            PasswordHash = "123456",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Nguyễn Cao Thái",
                            PasswordHash = "thai1969",
                            Role = "Editor",
                            Username = "thai_gv"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Nguyễn Văn A",
                            PasswordHash = "student1",
                            Role = "User",
                            Username = "sv_01"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Trần Thị B",
                            PasswordHash = "student2",
                            Role = "User",
                            Username = "sv_02"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Lê Văn C",
                            PasswordHash = "mod789",
                            Role = "Moderator",
                            Username = "moderator"
                        });
                });

            modelBuilder.Entity("duybao.data.Entities.Order", b =>
                {
                    b.HasOne("duybao.data.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("duybao.data.Entities.OrderDetail", b =>
                {
                    b.HasOne("duybao.data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("duybao.data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("duybao.data.Entities.Post", b =>
                {
                    b.HasOne("duybao.data.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("duybao.data.Entities.Product", b =>
                {
                    b.HasOne("duybao.data.Entities.CategoryProduct", "CategoryProduct")
                        .WithMany("Products")
                        .HasForeignKey("CategoryProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryProduct");
                });

            modelBuilder.Entity("duybao.data.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("duybao.data.Entities.CategoryProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("duybao.data.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("duybao.data.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
