// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using duybao.data;

#nullable disable

namespace duybao.data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260623184941_SeedGamingGearData")]
    partial class SeedGamingGearData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("duybao.data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cập nhật những xu hướng thời trang mới nhất",
                            Name = "Xu hướng thời trang"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mẹo phối đồ phong cách và ấn tượng",
                            Name = "Bí quyết phối đồ"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Thông tin sự kiện và ưu đãi đặc biệt",
                            Name = "Sự kiện & Khuyến mãi"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Chia sẻ bí quyết chăm sóc sắc đẹp",
                            Name = "Tư vấn làm đẹp"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tài liệu ASP.NET Core và SQL Server.",
                            Name = "Góc lập trình viên"
                        });
                });

            modelBuilder.Entity("duybao.data.Entities.CategoryProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CategoriesProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Chuột chuyên dụng cho game thủ",
                            Name = "Chuột Gaming"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bàn phím cơ, switch cao cấp",
                            Name = "Bàn phím Gaming"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tai nghe surround, micro chống ồn",
                            Name = "Tai nghe Gaming"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lót chuột kích thước lớn, bề mặt tối ưu",
                            Name = "Lót chuột Gaming"
                        });
                });

            modelBuilder.Entity("duybao.data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("duybao.data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("duybao.data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("duybao.data.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Content = "Khám phá những bí quyết phối đồ công sở giúp bạn luôn thanh lịch và chuyên nghiệp.",
                            CreatedDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/600x350/ffe0e0/999?text=Thời+Trang+Nữ",
                            Title = "Bí quyết phối đồ công sở thanh lịch cho nữ"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Content = "Cập nhật những xu hướng vest nam mới nhất năm 2026.",
                            CreatedDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/600x350/e0e0ff/999?text=Vest+Nam+2026",
                            Title = "Xu hướng vest nam 2026 - Lịch lãm và hiện đại"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Content = "Cách chọn đầm dạ hội phù hợp với vóc dáng và phong cách.",
                            CreatedDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/600x350/ffe0ff/999?text=Đầm+Dạ+Hội",
                            Title = "Đầm dạ hội - Lựa chọn hoàn hảo cho mọi sự kiện"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Content = "Xu hướng thời trang bền vững đang len lỏi vào môi trường công sở.",
                            CreatedDate = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/600x350/e0ffe0/999?text=Công+Sở+Bền+Vững",
                            Title = "Phong cách thời trang công sở bền vững"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Content = "Từ túi xách, giày dép đến trang sức - những phụ kiện giúp bạn hoàn thiện phong cách.",
                            CreatedDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://placehold.co/600x350/fff0e0/999?text=Phụ+Kiện",
                            Title = "Phụ kiện thời trang không thể thiếu cho nữ"
                        });
                });

            modelBuilder.Entity("duybao.data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("CategoryProductId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Logitech",
                            CategoryProductId = 1,
                            Description = "Chuột gaming không dây siêu nhẹ 63g, cảm biến HERO 25K, pin 70 giờ.",
                            DiscountPercentage = 12m,
                            ImageUrl = "https://resource.logitechg.com/d_transparent.gif/content/dam/gaming/en/products/pro-x-superlight/pro-x-superlight-black-gallery-1.png",
                            Name = "Logitech G Pro X Superlight",
                            Price = 3290000m,
                            Rating = 4.8m,
                            Sku = "LOG-GPX-001",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Razer",
                            CategoryProductId = 1,
                            Description = "Chuột gaming công thái học 59g, cảm biến Focus Pro 30K, switch quang học thế hệ 3.",
                            DiscountPercentage = 5m,
                            ImageUrl = "https://assets2.razerzone.com/images/pnx.assets/57c7af3e20e8a7b27b5a0e3a21e6a2b2/razer-deathadder-v3.png",
                            Name = "Razer DeathAdder V3",
                            Price = 2190000m,
                            Rating = 4.6m,
                            Sku = "RAZ-DAV3-002",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Corsair",
                            CategoryProductId = 1,
                            Description = "Chuột MMO 17 nút lập trình, cảm biến 18.000 DPI, Key Slider điều chỉnh bàn phím số.",
                            DiscountPercentage = 0m,
                            ImageUrl = "https://www.corsair.com/medias/sys_master/images/images/hf7/h6f/9540533280798/-CH-9304211-NA-Gallery-SCIMITAR-RGB-ELITE-01.png",
                            Name = "Corsair Scimitar RGB Elite",
                            Price = 1890000m,
                            Rating = 4.3m,
                            Sku = "COR-SCI-003",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Corsair",
                            CategoryProductId = 2,
                            Description = "Bàn phím cơ Cherry MX, switch PBT doubleshot, RGB per-key, khung nhôm.",
                            DiscountPercentage = 10m,
                            ImageUrl = "https://www.corsair.com/medias/sys_master/images/images/h9b/hcd/9540513792030/-CH-9109412-NA-Gallery-K70-RGB-PRO-01.png",
                            Name = "Corsair K70 RGB PRO",
                            Price = 3490000m,
                            Rating = 4.7m,
                            Sku = "COR-K70-004",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Razer",
                            CategoryProductId = 2,
                            Description = "Bàn phím cơ switch Analog quang học, Rapid Trigger, phím PBT doubleshot.",
                            DiscountPercentage = 8m,
                            ImageUrl = "https://assets2.razerzone.com/images/pnx.assets/ea2e2da7b6a4e08f8e6a1c2e3d4f5b6c/razer-huntsman-v3-pro.png",
                            Name = "Razer Huntsman V3 Pro",
                            Price = 4890000m,
                            Rating = 4.5m,
                            Sku = "RAZ-HV3-005",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Logitech",
                            CategoryProductId = 2,
                            Description = "Bàn phím cơ không dây low-profile, switch GL Tactile, RGB Lightsync.",
                            DiscountPercentage = 15m,
                            ImageUrl = "https://resource.logitechg.com/d_transparent.gif/content/dam/gaming/en/products/g915-tkl/g915-tkl-gallery-1.png",
                            Name = "Logitech G915 TKL",
                            Price = 4290000m,
                            Rating = 4.4m,
                            Sku = "LOG-G915-006",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 7,
                            Brand = "HyperX",
                            CategoryProductId = 3,
                            Description = "Tai nghe không dây 7.1 surround, pin 30 giờ, micro chống ồn, driver 53mm.",
                            DiscountPercentage = 20m,
                            ImageUrl = "https://media.kingston.com/hyperx/cloud/hhsc1x-ba-xxl/cloud-ii-wireless-gallery-1.jpg",
                            Name = "HyperX Cloud II Wireless",
                            Price = 2690000m,
                            Rating = 4.9m,
                            Sku = "HYX-CC2-007",
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 8,
                            Brand = "SteelSeries",
                            CategoryProductId = 3,
                            Description = "Tai nghe không dây 360° Spatial Audio, Bluetooth + 2.4GHz, pin 38 giờ.",
                            DiscountPercentage = 10m,
                            ImageUrl = "https://media.steelseriescdn.com/thumbs/catalog/items/61486/7a3f3b3b3b3b3b3b3b3b3b3b3b3b3b3b/61486_Arctis_Nova_7_Black_1.png",
                            Name = "SteelSeries Arctis Nova 7",
                            Price = 3190000m,
                            Rating = 4.7m,
                            Sku = "SS-AN7-008",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Razer",
                            CategoryProductId = 3,
                            Description = "Tai nghe không dây eSports, driver TriForce 50mm, microphone HyperClear Super Wideband.",
                            DiscountPercentage = 7m,
                            ImageUrl = "https://assets2.razerzone.com/images/pnx.assets/5c6b7d8e9f0a1b2c3d4e5f6a7b8c9d0e/razer-blackshark-v2-pro.png",
                            Name = "Razer BlackShark V2 Pro",
                            Price = 3890000m,
                            Rating = 4.6m,
                            Sku = "RAZ-BSV2-009",
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 10,
                            Brand = "SteelSeries",
                            CategoryProductId = 4,
                            Description = "Lót chuột kích thước lớn 900x400mm, bề mặt vải micro-woven, đế cao su chống trượt.",
                            DiscountPercentage = 0m,
                            ImageUrl = "https://media.steelseriescdn.com/thumbs/catalog/items/63824/63824_QcK_Heavy_XXL_1.png",
                            Name = "SteelSeries QcK Heavy XXL",
                            Price = 690000m,
                            Rating = 4.8m,
                            Sku = "SS-QCK-010",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Razer",
                            CategoryProductId = 4,
                            Description = "Lót chuột 940x410mm, bề mặt sợi dệt siêu mịn, tối ưu tracking cho mọi cảm biến.",
                            DiscountPercentage = 5m,
                            ImageUrl = "https://assets2.razerzone.com/images/pnx.assets/d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9/razer-gigantus-v2-xxl.png",
                            Name = "Razer Gigantus V2 XXL",
                            Price = 590000m,
                            Rating = 4.5m,
                            Sku = "RAZ-GIG-011",
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Logitech",
                            CategoryProductId = 4,
                            Description = "Lót chuột 900x400mm, bề mặt tối ưu cho game thủ, tương thích Logitech G Powerplay.",
                            DiscountPercentage = 10m,
                            ImageUrl = "https://resource.logitechg.com/d_transparent.gif/content/dam/gaming/en/products/g840-xl/g840-xl-gallery-1.png",
                            Name = "Logitech G840 XL",
                            Price = 790000m,
                            Rating = 4.3m,
                            Sku = "LOG-G840-012",
                            StockQuantity = 20
                        });
                });

            modelBuilder.Entity("duybao.data.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerEmail")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ReviewerName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Chuột quá nhẹ, cảm giác cầm cực tốt!",
                            CreatedDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Rating = 5,
                            ReviewerName = "GamerPro99"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Pin trâu, không dây nhưng không lag.",
                            CreatedDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Rating = 4,
                            ReviewerName = "TechReviewer"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Switch Cherry êm, build chắc tay!",
                            CreatedDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 4,
                            Rating = 5,
                            ReviewerName = "KeyboardFan"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Âm thanh surround cực hay, đeo lâu không đau tai.",
                            CreatedDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 7,
                            Rating = 5,
                            ReviewerName = "SoundMaster"
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Lót chuột to, bề mặt mịn, rê chuột không bị cấn.",
                            CreatedDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 10,
                            Rating = 5,
                            ReviewerName = "MousePadKing"
                        });
                });

            modelBuilder.Entity("duybao.data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Quản trị viên hệ thống",
                            PasswordHash = "123456",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Nguyễn Cao Thái",
                            PasswordHash = "thai1969",
                            Role = "Editor",
                            Username = "thai_gv"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Nguyễn Văn A",
                            PasswordHash = "student1",
                            Role = "User",
                            Username = "sv_01"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Trần Thị B",
                            PasswordHash = "student2",
                            Role = "User",
                            Username = "sv_02"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Lê Văn C",
                            PasswordHash = "mod789",
                            Role = "Moderator",
                            Username = "moderator"
                        });
                });

            modelBuilder.Entity("duybao.data.Entities.Order", b =>
                {
                    b.HasOne("duybao.data.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("duybao.data.Entities.OrderDetail", b =>
                {
                    b.HasOne("duybao.data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("duybao.data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("duybao.data.Entities.Post", b =>
                {
                    b.HasOne("duybao.data.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("duybao.data.Entities.Product", b =>
                {
                    b.HasOne("duybao.data.Entities.CategoryProduct", "CategoryProduct")
                        .WithMany("Products")
                        .HasForeignKey("CategoryProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryProduct");
                });

            modelBuilder.Entity("duybao.data.Entities.Review", b =>
                {
                    b.HasOne("duybao.data.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("duybao.data.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("duybao.data.Entities.CategoryProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("duybao.data.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("duybao.data.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("duybao.data.Entities.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
